FROM golang:1.24 as build

RUN mkdir -p /build
WORKDIR /build/

# Force the go compiler to use modules
ENV GO111MODULE=on
ENV LOGGER_LEVEL="debug"
ENV LOGGER_FORMAT="pretty"
ARG GO_SERVICE=""

# We want to populate the module cache based on the go.{mod,sum} files.
COPY go.mod .

# This is the ‘magic’ step that will download all the dependencies that are specified in
# the go.mod and go.sum file.
# Because of how the layer caching system works in Docker, the  go mod download
# command will _ only_ be re-run when the go.mod or go.sum file change
# (or when we add another docker instruction below this line)
RUN go mod download

# Add code refresh package
RUN go install github.com/cespare/reflex@latest
RUN echo "-r '(\.go$|go\.mod)' -s -- sh -c 'go run -race cmd/${GO_SERVICE}/*.go start --config services/${GO_SERVICE}/.config.yml'" >> /reflex.conf
ENTRYPOINT ["reflex", "--decoration=none", "-c", "/reflex.conf"]

COPY . .

# Required because go.sum does not exist yet - ignored in .dockerignore
RUN go mod tidy

EXPOSE 6060
EXPOSE 80
