name: Check golang services for vulnerabilities

on:
  workflow_call:
    inputs:
      workspace:
        type: string
        required: true

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee
        with:
          go-version-input: 1.24
          go-package: ./...
          work-dir: services/${{ inputs.workspace }}/app/v1
